### ISSUE TITLE
Feature Request: keep test results when gemini test runing with --grep argument

### ISSUE THREAD

**Issue by generalov** [gemini-testing/html-reporter#102]
1. Run `gemini update`
2. Run `gemini test --grep "my suite"`

Actual: `data.js` contains only "my suite" results.
Expected: `data.js` contains all results that are taken by the `gemini update` and updated test results for 'my suite'.

It looks like the reusing of test results this already implemented in the `gui`  report builder https://github.com/gemini-testing/html-reporter/blob/master/lib/gui/tool-runner-factory/base-tool-runner.js#L56 but not in CLI reporting tool https://github.com/gemini-testing/html-reporter/blob/master/lib/report-builder-factory/report-builder.js . It would be nice if they shared the same implementation. Perhaps the reusing of results could be triggered by CLI argument `--reuse` or something like that.

**Comment by DudaGod** [comment]
Hello.

> Actual: data.js contains only "my suite" results.
Expected: data.js contains all results that are taken by the gemini update and updated test results for 'my suite'.

It makes no sense. Each run of tests should generate new data.js file with current test results.
To fix your problem you should use gui.

Moreover gemini is deprecated, try to use hermione - https://github.com/gemini-testing/hermione.
