### ISSUE TITLE
Не работают скриншоты в hermione-html-report

### ISSUE THREAD

**Issue by KingManiya** [gemini-testing/html-reporter#148]
Если в конфиге hermione изменить путь до отчета:
```
  plugins: {
    'html-reporter/hermione': {
      path: 'tests/hermione/html-report',
    },
  }
```
То папка с отчетом создается, но при запуске hermione gui - страница не видит скриншоты. 
<img width="552" alt="screenshot at 23 21-26-55" src="https://user-images.githubusercontent.com/3191925/47382312-ae606d80-d70a-11e8-834e-f0640de72890.png">

При исправлении пути на path: 'tests/hermione/**hermione-html-report**' репорт нормально показывает и принимает скриншоты.
<img width="555" alt="screenshot at 23 21-27-22" src="https://user-images.githubusercontent.com/3191925/47382317-b3252180-d70a-11e8-9b86-763dac3e933a.png">

**Comment by Mefistopel** [comment]
У меня тоже не работают скриншоты в отчёте. 
В папке html-reports скриншоты создаются, но при запуске браузеров Yandex и Chrome скрины не подгружаются.
![image](https://user-images.githubusercontent.com/16778030/62991995-07f17e80-be7c-11e9-8c95-ef8d9a82bfc5.png)

Но если запускать этот же отчёт через Mozilla Firefox, то всё отлично
![image](https://user-images.githubusercontent.com/16778030/62992035-28b9d400-be7c-11e9-8334-7aec33f5ca3b.png)

**Версии:**
Yandex: 19.7.2.455
Chrome: Версия 76.0.3809.100 (Официальная сборка), (64 бит)
Mozilla Firefox: 68.0.1 (64-битный)
html-reporter: ^4.11.1
hermione: ^2.7.1
