### ISSUE TITLE
Страница прыгает при ленивой загрузке картинок

### ISSUE THREAD

**Issue by dizel3d** [gemini-testing/html-reporter#150]
Включена опция ленивой загрузки картинок.
Страница прыгает, когда просматриваешь репорт снизу вверх. Как я понимаю, это происходит потому, что плейсхолдерам картинок не заданы размеры. По мере прокрутки страницы картинки подгружаются, увеличивая высоту страницы, сдвигая окно просмотра вверх.

**Comment by sipayRT** [comment]
привет

так мы же заранее не знаем размеры картинок. моно выставлять какие-то дефолтные размеры, но оно явно не спасет, т.к. ты не угадаешь размеры

**Comment by dizel3d** [comment]
А почему мы не знаем размеры? Их в `data.js` нельзя добавить?

**Comment by dizel3d** [comment]
Вижу, что работа в этом направлении идет https://github.com/gemini-testing/hermione/pull/330

**Comment by DudaGod** [comment]
Верно идет. Размеры мы будем прокидывать из gemini и hermione и проставлять по мере выполнения тестов.

**Comment by 4eb0da** [comment]
Вроде исправлено, наверно, можно закрыть?

**Comment by sipayRT** [comment]
да, уже исправили. закрываем
