### ISSUE TITLE
CORS Error in index.html 

### ISSUE THREAD

**Issue by mchennig** [gemini-testing/html-reporter#151]
Hi,
after opening the index.html file from a recently generated gemini html-report I get the following errors, which can be reproduced in Chrome, IE, Edge and Firefox under Windows 10:

Chrome 70:
`index.html:1 Access to resource at 'file:///C:/events' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

Firefox 62:
`Firefox can’t establish a connection to the server at file:///events. report.min.js:39:116091`

IE 11:
`SCRIPT438: Object doesn't support property or method 'assign'. report.min.js (39,64507)`

Edge:
`SCRIPT16389: Unknown Error. report.min.js (38,59117)`

The problem seems to be somehow related to the data.js file, because if I replace the existing data.js with one from an older html report (~1 month old) the report.min.js correctly loads the page.

**Comment by DudaGod** [comment]
Hello.
It's strange. Do you still reproduce this problem?

**Comment by mchennig** [comment]
Hi, I'm not using gemini anymore since it was deprecated. I will close this issue since I can't reproduce.
