### ISSUE TITLE
Save control state in url

### ISSUE THREAD

**Issue by isqua** [gemini-testing/html-reporter#174]
<img width="1103" alt="hermione-report" src="https://user-images.githubusercontent.com/529247/49947482-6ab40400-ff02-11e8-8ebc-3283d38bd3e9.png">

to save control state between refreshes (mostly) and allow to share urls

And add anchor of specific test case to url, e.g. `hermione-report/index.html#tpid123456-chrome-phone`

**Comment by DudaGod** [comment]
Hello.

The opportunity to give a link to the test is already implemented in the report:
<img width="462" alt="share_url_on_test" src="https://user-images.githubusercontent.com/5900697/80187472-5d3f7b80-8618-11ea-89a2-60239c2467e5.png">

State between refreshes works too using local storage.
