### ISSUE TITLE
How to override settings from cli?

### ISSUE THREAD

**Issue by SomeBdyElse** [gemini-testing/html-reporter#20]
In the README.md it says: "Also there is ability to override plugin parameters by CLI options or environment variables (see configparser)."

As html-reporter has a dash in its name, I am not sure how to convert the properties to kebab case. 

Here is what I tried (to no avail)
`gemini test --plugins-html-reporter-path override`
`gemini test --plugins-html-reporter-path=override`
`gemini test --plugins-htmlreporter-path override`

**Comment by SomeBdyElse** [comment]
I found the solution myself: `gemini test --path=override`

**Comment by j0tunn** [comment]
OMG. Looks like a bug. It should be something like `gemini-test --html-reporter-path`. But looks like configparser doesn't recognize cli prefixes yet. We will fix this, thanks for the report

**Comment by j0tunn** [comment]
@SomeBdyElse this was fixed in `html-reporter@1.0.0`.
From now to override `path` option you should pass `--html-reporter-path` option.

**Comment by SomeBdyElse** [comment]
And you updated the README.md right away 👍 . Thank you!
