### ISSUE TITLE
Открывается пустая страница при попытке просмотреть инфо по пройденному тесту

### ISSUE THREAD

**Issue by ph4ud** [gemini-testing/html-reporter#234]
Установил html-reporter на гермиону. После прохождения теста попытался открыть репорт и посмотреть инфо по тесту. Открылась пустая страница, при этом в консоли браузера падает ошибка
Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Burls%2C%20hubs%2C%20endUsers%2C%20adminUser%2C%20updateReports%2C%20deleteWhenDone%2C%20reportNamePostfix%2C%20fileNameForTestsData%2C%20studioComponentSecret%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 

В чем может быть причина?

**Comment by sipayRT** [comment]
привет

без данных о твоем окружении (настройки гермионы, OS, браузер, выполняемый тест) сложно понять что именно произошло

можешь хоть сам отчет скинуть?

**Comment by ph4ud** [comment]
ОС - Win10, браузер - Chrome 75.0.3770.100
Тест примитивный
`describe('cheking report', function() {
  it('making html report', function() {
    return this.browser
      .url('yandex.ru')
      .pause(3000)
      .assertView('testReport', 'body');
  });
});
`
Конфиг тоже

`module.exports = {
  baseUrl: 'http://',
  sets: {
    allTests: {
      files: './tests/',
    },
  },

  browsers: {
    tenta69: {
      windowSize: {
        width: 1366,
        height: 768,
      },
      desiredCapabilities: {
        browserName: 'chrome',
      },
      resetCursor: true,
      screenshotsDir: function() {
        return path.resolve(process.cwd(), './expected/tenta69');
      },
      compositeImage:true,
      },
  plugins:{
    'html-reporter/hermione':{
      enabled: true,
      path:'./bugReports/hermione-html-report'
    }
  }
};
`
отчет залил сюда
https://github.com/ph4ud/hermione/

Да, кстати, рефы к тесту намерено сняты так, чтобы при прохождении выдавалось image comparison failed

**Comment by DudaGod** [comment]
@ph4ud привет. Отчет по твоей ссылке уже не доступен. Можешь пожалуйста убедиться, что данная проблема все еще воспроизводится? И если да, то предоставить отчет еще раз.
Спасибо.

**Comment by DudaGod** [comment]
Так как данных нет, то issue закрываю. Если проблема воспроизведется, заведи пожалуйста новый issue. Спасибо.
