### ISSUE TITLE
Пустая страница при использовании getMeta

### ISSUE THREAD

**Issue by R1ZEN** [gemini-testing/html-reporter#240]
Привет!

Репорт обновляется на пустую страницу при открытии теста.

Код для воспроизведения:
```js
it('test', function() {
    return this.browser
        .setMeta('foo', [{url: 'https://yandex.by/'}])
        .getMeta('foo')
        .then(([foo]) =>  this.browser.url(foo.url));
});
```

Plugins:
```
plugins: {
        'html-reporter/hermione': {
            enabled: true,
            defaultView: 'all',
            path: 'e2e-report'
        },
       ...
}
```
 
`npx envinfo`:
<pre>
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 956.82 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.2 - ~/.nvm/versions/node/v10.15.2/bin/node
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.2/bin/npm
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 10.14. - /usr/bin/gcc
    Git: 2.21.0 - /usr/local/bin/git
  Databases:
    SQLite: 3.24.0 - /usr/bin/sqlite3
  Browsers:
    Firefox Developer Edition: 68.0
    Safari: 12.1.1
</pre>

**Comment by R1ZEN** [comment]
Залил [PR](https://github.com/gemini-testing/html-reporter/pull/241) с фиксом, поревьюйте пожалуйста)

**Comment by CatWithApple** [comment]
merged
