### ISSUE TITLE
chrome and %5С

### ISSUE THREAD

**Issue by kelebro13** [gemini-testing/html-reporter#27]
Добрый день! Не отображаются скриншоты в отчёте в браузере chrome: в url обратный слеш заменяется на %5C.
![html-report](https://user-images.githubusercontent.com/16813236/33591985-83ac9f40-d9aa-11e7-8b7e-2109d54baaf9.jpg)

p.s.: корректно работает только в firefox.

**Comment by DudaGod** [comment]
Привет.

Подскажи пожалуйста, какая у тебя версия html-reporter-а?
Мы вчера катили версию, возможно в ней бага. Сегодня проверим.

Как временное решение - откатись на предыдущую версию.
Спасибо за информацию.

**Comment by kelebro13** [comment]
версия 1.0.0

**Comment by tylertrotter** [comment]
I believe I have the same problem. I think it is caused by windows using backslashes. I wonder if you just encode the image path that would fix it.

**Comment by Hrommi** [comment]
html-reporter@2.5.0 проблема с путями в chrome по прежнему актуальна. Как можно решить?

**Comment by jayveeMaui** [comment]
Instead of returning just pathToImage at createpath() on lib/server-utils.js I did pathtoImage.replace(/\\/g,''). Is it a good Idea? seems like the path module is causing the backslash.

**Comment by Astimus** [comment]
I found workaround for this issue. I have set path property to empty string:
```
plugins: {
            'html-reporter/gemini': {
                enabled: true,
                path: '',
                defaultView: 'all',
                baseHost: 'test.com'
            }
        }
```

**Comment by SokolovAlex** [comment]
it problem in logic in server-utils
https://github.com/gemini-testing/html-reporter/blob/master/lib/server-utils.js#L42

when author uses lib "path", lib generate path depends of OS. it`s necessery for server usage, but it's wrong for client usage. Paths generated on window don't work on client

the generated path uses on clinet in background.

for client path you math replace path.join
to

components.reduce((createdPath, component) =>
createdPath ? ${createdPath}/${component.replace('\\', '/')} : component, '');

**Comment by greyseer256** [comment]
I am also experiencing this issue using `html-reporter` `4.6.0` on Windows 7. The problem seems to be that Windows paths use `\` separators while `html-reporter` assumes POSIX `/` separators. [This line in particular](https://github.com/gemini-testing/html-reporter/blob/master/lib/static/components/state/screenshot.js#L88) splits on `/` when generating the `background-image` urls for the report. So `\`s are URI encoded as `%5C`, which results in invalid urls, preventing the images from being displayed.

**Comment by wrager** [comment]
Any updates on this issue? 🤔

FF also can't render images on Windows. Which browser should we use to avoid this 1.5 year old bug?

![image](https://user-images.githubusercontent.com/1602784/60975226-4b644480-a334-11e9-95b8-f7bc707626d0.png)

**Comment by wrager** [comment]
I've made a rough tampermonkey script for showing the screenshots, hope this helps.

```
(function() {
    'use strict';

    function fix() {
        setTimeout(function() {
            const screenshots = document.querySelectorAll('.image-box__screenshot');
            for (let screenshot of screenshots) {
                screenshot.style.backgroundImage = screenshot.style.backgroundImage.replace(/%5C/, '/');
            }
        }, 100);
    }
    document.onscroll = document.onclick = fix;
    fix();
})();
```
