### ISSUE TITLE
Documentation / configuration

### ISSUE THREAD

**Issue by hippee-lee** [gemini-testing/html-reporter#3]
I'm trying to use this. Out project was previously using the built in html reports from gemini but they removed them last week.

I have my gemini yml configured thus:
```
system:
  plugins:
    'html-reporter': {
      enabled: true
    }
```

I've tried running `gemini test --reporter html gemini/tests/set1/alert.js`  but get the followign error: 
`Error: Cannot find module 'html-reporter' or 'gemini-html-reporter'`

html-reporter is installed in my node_modules. I'm sure I am missing something but its hard to say what as using the html reporter as a plugin to gemini seems pretty new. 
Any direction to docs would be a big help.

**Comment by rostik404** [comment]
Hi!
In the last version of `gemini`, you should not pass option `--reporter html`, you just need to plug `html-reporter` in your config file.

`Error: Cannot find module 'html-reporter' or 'gemini-html-reporter'` - you can get this error only if `html-reporter` is not installed in `node_modules` of **your project**. Maybe you installed `html-reporter` in `node_modules` of gemini?

**Comment by hippee-lee** [comment]
Thanks for the feedback. I have tried uninstalling / reinstalling `html-reporter` several times with npm. Here is a screen shot of the following:
1. .gemini.conf.yml
2. html-reporter in my node_modules folder
3. THe Error I get when running `gemini test gemini/tests/set1/alert.js 
`

Is there anything else I can do to help diagnose this issue? 
![screen shot 2017-06-13 at 8 19 36 am](https://user-images.githubusercontent.com/433692/27090208-6ee11cee-5011-11e7-997d-19c8c8037c20.png)

**Comment by rostik404** [comment]
Have you tried to install `html-reporter` in the same `node_modules` directory as `gemini`? I don't see `gemini` in `node_modules` on your screenshot.

**Comment by hippee-lee** [comment]
You sir are correct. installing it with `npm install -g html-reporter` solved my issue.
Makes sense that they would need to be installed in the same place (duh). Sorry i missed that.
