### ISSUE TITLE
Названия папок / Folder names

### ISSUE THREAD

**Issue by wayheming** [gemini-testing/html-reporter#309]
Здравствуйте подскажите как настроить название папок чтобы соответствовали названию теста?
http://prntscr.com/r80gzn

Hello, tell me how to configure the name of the folders to match the name of the test?
http://prntscr.com/r80gzn

**Comment by sipayRT** [comment]
Привет
Для самого отчета - никак ,т.к. это считается внутренним устройством пакета

Для самого проекта (хранения эталонов) в hermione можно использовать опцию [screenshotsdir](https://github.com/gemini-testing/hermione#screenshotsdir)

**Comment by wayheming** [comment]
@sipayRT спасибо за ответ, я уже использую опцию screenshotsDir 
`screenshotsDir: '../../tests/html-report/images',`
  
раньше использовал gemini и там папки имели названия тестов

**Comment by sipayRT** [comment]
для gemini используется другой способ парсинга тестов, поэтому там просто создавалась вложенность по названию.
в hermione, к сожалению, такого сделать пока нельзя

> screenshotsDir: '../../tests/html-report/images'

как-то ты странно указал хранение эталонов, т.к. по идее это папка отчета, которая может удаляться (т.е. это временные файлы)

**Comment by wayheming** [comment]
@sipayRT жаль( но спасибо за оперативность
за хранение сейчас посмотрю
