### ISSUE TITLE
why html-reporter use fixed server port value

### ISSUE THREAD

**Issue by nsklyarov** [gemini-testing/html-reporter#318]
Hi! Good plugin!
but why html-reporter use fixed server port value?
Maybe this value would be much more convenient to take from the plugin settings in hermione.config

**Comment by sipayRT** [comment]
Hi
You can change it with `--port|-p` option.
See more options by `npx hermione gui --help`

**Comment by DudaGod** [comment]
Hello. I close it, due to the fact that it can be configured using CLI.
