### ISSUE TITLE
Как можно сбросить результаты всех тестов?

### ISSUE THREAD

**Issue by fantazer** [gemini-testing/html-reporter#372]
Добрый день, спасибо за вашу работу. Удобный инструмент.

Подскажите, как можно сбросить результаты всех тестов, чтобы привести html-reporter к начальному состоянию (когда ни одного теста не было запущенно)

**Comment by DudaGod** [comment]
> Добрый день, спасибо за вашу работу. Удобный инструмент.

Привет, пожалуйста.

> Подскажите, как можно сбросить результаты всех тестов, чтобы привести html-reporter к начальному состоянию (когда ни одного теста не было запущенно)

Сбросить результаты прогона можно с помощью удаления директории, которая указана в поле `path` плагина. По умолчанию сохраняет в `workDir/hermione-report`. Т.е. достаточно выполнить `rm -rf hermione-report` находясь в папке проекта.

Возможно в будущем для этого заведем отдельную кнопку в интерфейсе, чтобы быстро почистить результат прогона.
