### ISSUE TITLE
Doesn't work with nodejs 16

### ISSUE THREAD

**Issue by dfilatov** [gemini-testing/html-reporter#408]
Seems html-reporter doesn't work with nodejs16/npm8. There's an error while `npm i`:
```
npm ERR! In file included from ../src/integer.cpp:1:
npm ERR! In file included from ../src/integer.hpp:3:
npm ERR! In file included from /Users/dfilatov/Library/Caches/node-gyp/16.13.0/include/node/node.h:63:
npm ERR! In file included from /Users/dfilatov/Library/Caches/node-gyp/16.13.0/include/node/v8.h:30:
npm ERR! /Users/dfilatov/Library/Caches/node-gyp/16.13.0/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
npm ERR! /Library/Developer/CommandLineTools/usr/include/c++/v1/type_traits:660:50: note: 'remove_cv' declared here
npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
npm ERR!                                                  ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/integer/src/integer.o] Error 1
```
Looks like the problem with `integer` module which is used by `better-sqlite3`. 
Probably it makes sense to upgrade `better-sqlite3` to version 7.

**Comment by DudaGod** [comment]
Hello.

It looks like that upgrade `better-sqlite3` to version 7 should not lead to the problems judging by the changes in this version - https://github.com/JoshuaWise/better-sqlite3/releases/tag/v7.0.0.

We will try to update it and check that everything works fine with node@12-16.
Thank you.

**Comment by dfilatov** [comment]
@DudaGod Hi, is there any progress? It’s a blocker for us to upgrade lts version of node.js

**Comment by DudaGod** [comment]
@dfilatov Hello. We will merge this PR - https://github.com/gemini-testing/html-reporter/pull/410 today. Link on task - https://nda.ya.ru/t/1P7ZgmFD4X5dzZ.

**Comment by dicrtarasov** [comment]
Теперь работает, спасибо!
