### ISSUE TITLE
Incorrect report when load image fail.

### ISSUE THREAD

**Issue by dicrtarasov** [gemini-testing/html-reporter#436]
Hermione log output:
```
Total: 846 Passed: 842 Failed: 1 Skipped: 3 Retries: 6
```

html-report incorrectly report "Failed: 0" when actually there are 1 failed test. 
Failed test is not displayed in tree at all.

![image](https://user-images.githubusercontent.com/35159934/190829158-bec764ac-9a66-4c8e-b528-8bb72a18ff7e.png)

Json-report says 1 test failed, that is correct:

![image](https://user-images.githubusercontent.com/35159934/190829261-5a0e0f5d-d7be-4e24-996e-b87903cb5ee8.png)

Hermione log contains Html-report error while loading png-image:

```
Html-reporter runtime error: NestedError: Can't load png file /place/db/www/login/.tests/hermione/screens/c546b0c/chrome/zapolnili_pole_dlya_zapreshchennogo_znacheniya.png
    at exports.fromFile (/place/db/www/login/.tests/node_modules/looks-same/lib/png-image/index.js:33:15)
     at async Promise.all (index 0)
     at async Object.exports.readPair (/place/db/www/login/.tests/node_modules/looks-same/lib/utils.js:21:35)
 Caused By: Error: Invalid file signature
     at module.exports.Parser._parseSignature (/place/db/www/login/.tests/node_modules/pngjs/lib/parser.js:48:18)
     at module.exports.ChunkStream._processRead (/place/db/www/login/.tests/node_modules/pngjs/lib/chunkstream.js:160:13)
     at module.exports.ChunkStream._process (/place/db/www/login/.tests/node_modules/pngjs/lib/chunkstream.js:175:14)
     at module.exports.ChunkStream.write (/place/db/www/login/.tests/node_modules/pngjs/lib/chunkstream.js:57:8)
     at module.exports.ChunkStream.end (/place/db/www/login/.tests/node_modules/pngjs/lib/chunkstream.js:69:10)
     at exports.PNG.PNG.end (/place/db/www/login/.tests/node_modules/pngjs/lib/png.js:100:16)
     at exports.PNG.PNG.parse (/place/db/www/login/.tests/node_modules/pngjs/lib/png.js:90:8)
     at /place/db/www/login/.tests/node_modules/looks-same/lib/png-image/index.js:12:13
     at new Promise (<anonymous>)
     at parseBuffer (/place/db/www/login/.tests/node_modules/looks-same/lib/png-image/index.js:10:12)
     at Object.exports.fromBuffer (/place/db/www/login/.tests/node_modules/looks-same/lib/png-image/index.js:38:23)
     at exports.fromFile (/place/db/www/login/.tests/node_modules/looks-same/lib/png-image/index.js:31:30)
     at async Promise.all (index 0)
     at async Object.exports.readPair (/place/db/www/login/.tests/node_modules/looks-same/lib/utils.js:21:35)
 (node:106) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
Tests FAILED !!!
```

So, when png-image load error, then failed test is not displayed in the report tree and total stats.

**Comment by DudaGod** [comment]
Hello.

Thank you, I will try to reproduce this problem.

**Comment by dicrtarasov** [comment]
Updated to latest version.
Now, no information about corrupted image file :((
```
Html-reporter runtime error: Error: Input buffer contains unsupported image format
(node:101) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)
```

**Comment by dicrtarasov** [comment]
> Hello.
> 
> Thank you, I will try to reproduce this problem.

Чтобы воспроизвести данную проблему, нужно сделать следующее - испортить снятый файл шаблона (внутри него данные изображения испортить так чтобы его нельзя было открыть, например, в файл png положить текст "123") . Тогда при генерации отчета будет данная ошибка.

Проблема в некорректном поведении при битом файле. Либо скрывает этот тест (не учитывает), либо вообще падает. А нужно чтобы при битой картинке выдавалось сообщение об ошибке с путем файла (в последней версии из текста ошибки исключили путь битого файла и теперь найти какой файл с проблемой стало невозможно), а при отображении отчета этот битый файл пусть себе либо не отображается, либо крестиком. 

Необходима правильная реакция на ситуацию с битым файлом, иначе использовать становится невозможно и какой-то битый файл из тысяч полностью ломает работу. Непонятно что делать дальше.

**Comment by KuznetsovRoman** [comment]
Привет

Можешь попробовать обновить `looks-same` до 8.1.0?

**Comment by dicrtarasov** [comment]
Так его нет у меня в зависимостях, а html-report сам подтягивает нужную ему версию.

**Comment by KuznetsovRoman** [comment]
Хм. По стектрейсу видно, что используется версия ниже 8.1.0

С какими версиями `hermione` и `html-reporter` был создан этот стектрейс?

**Comment by dicrtarasov** [comment]
```
adfox-tests-hermione@1.0.0 /Users/dicrtarasov/Projects/interfaces/.tests
├─┬ hermione@5.6.1
│ └── looks-same@8.1.0
└─┬ html-reporter@9.7.1
  └── looks-same@8.1.0 deduped
```

**Comment by KuznetsovRoman** [comment]
Попробуй удалить `node_modules` и установить зависимости заново. Там явно не 8.1.0 используется

**Comment by dicrtarasov** [comment]
```
{
  "name": "looks-same",
  "version": "8.1.0",
  "description": "Pure node.js library for comparing PNG-images, taking into account human color perception.",
  "main": "index.js",
  "types": "index.d.ts",
  "directories": {
    "test": "test"
  },
```

**Comment by dicrtarasov** [comment]
Причем с прежними версиями хоть отображался путь проблемного файла в ошибке, а с новой версией просто ошибка и неизвестно в каком png-файле ее искать.

**Comment by KuznetsovRoman** [comment]
Будет исправлено в https://github.com/gemini-testing/hermione/pull/703

**Comment by dicrtarasov** [comment]
ну можно было и не падать через throw, а выдать ошибку как будто этот файл отсутствует (reference not found). Тогда можно видеть отчет и переснять отсутствующие/испорченные файлы.

**Comment by KuznetsovRoman** [comment]
Тут надо подумать: это зависит от того, как эти испорченные файлы появились. Если эти рефки хранятся в `git lfs`, например, и разработчик пока не сделал `git lfs pull`, то вряд ли затирать их - хорошая идея. Вряд ли референсы как-то сами сломаются, если их не трогают

**Comment by dicrtarasov** [comment]
да, бывает что они содержат lfs reference. Но бывает и другие виды испорченных файлов. Проще всего - отловить ошибку чтения файла, например try Image.compare catch ImageError и пойти по пути как будто файл не существует.

**Comment by KuznetsovRoman** [comment]
> бывают и другие виды испорченных файлов

Сейчас посмотрим

**Comment by DudaGod** [comment]
Проблема исправлена. Закрываю.
