### ISSUE TITLE
Would it be possible to rename this package to something less generic? e.g. gemini-html-reporter

### ISSUE THREAD

**Issue by akiellor** [gemini-testing/html-reporter#5]

**Comment by sipayRT** [comment]
hm... but for what?

**Comment by akiellor** [comment]
@sipayRT it actually made it pretty difficult to find the plugin dependency through npmjs.org, there was little reference to gemini from the search.

**Comment by sipayRT** [comment]
in the future it can be common plugin for gemini and hermione
