### ISSUE TITLE
node 22 compatibility

### ISSUE THREAD

**Issue by vaseker** [gemini-testing/html-reporter#546]
### Contribution

- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/gemini-testing/html-reporter/blob/master/CONTRIBUTING.md))

### Describe the user story

While installing html-reporter in node@22 environment, it crashes caused by better-sqlite@8 dependency.
Bumping better-sqlite to actual major 9 resolves installation issue.
Next compatibility issue was found in `@gemini-testing/sql.js` while running package's tests: `Html-reporter runtime error: Error: Cannot find module '@gemini-testing/sql.js/dist/sql-wasm.wasm'`. Maybe it will be enough to rebase your fork-package to solve compatibility issues.
<img width="1170" alt="Снимок экрана 2024-05-18 в 11 50 18" src="https://github.com/gemini-testing/html-reporter/assets/1942271/339c8dba-8f10-4f88-ba16-17793ca1a270">

### Describe the solution you'd like

html-reporter and node 22 compatibility

**Comment by sipayRT** [comment]
fixed in [html-reporter@10.0.0](https://github.com/gemini-testing/html-reporter/releases/tag/v10.0.0)

**Comment by sipayRT** [comment]
fixed in [html-reporter@10.0.0](https://github.com/gemini-testing/html-reporter/releases/tag/v10.0.0)
